### ISSUE TITLE
Error: Connection lost

### ISSUE THREAD

**Issue by MillesC** [Vinicius-Santos-Guedes/Chat-Simples-para-implementacao#1]
Consegui instalar e conectar no BD, mas logo após ocorre este erro.
Pode me ajudar?
Obrigado.
https://prnt.sc/r6m3hl

C:\N\Chat-Simples-para-implementacao\chat-demonstracao\chat-backend\src>node index.js
HTTP server started on http://localhost:8080
WS server started on ws://localhost:8888
Successfully connected to the DB.
events.js:200
      throw er; // Unhandled 'error' event
      ^

Error: Connection lost: The server closed the connection.
    at Protocol.end (C:\N\Chat-Simples-para-implementacao\chat-demonstracao\chat-backend\node_modules\mysql\lib\protocol\Protocol.js:112:13)
    at Socket.<anonymous> (C:\N\Chat-Simples-para-implementacao\chat-demonstracao\chat-backend\node_modules\mysql\lib\Connection.js:94:28)
    at Socket.<anonymous> (C:\N\Chat-Simples-para-implementacao\chat-demonstracao\chat-backend\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:228:7)
    at endReadableNT (_stream_readable.js:1185:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
Emitted 'error' event on Connection instance at:
    at Connection._handleProtocolError (C:\N\Chat-Simples-para-implementacao\chat-demonstracao\chat-backend\node_modules\mysql\lib\Connection.js:423:8)
    at Protocol.emit (events.js:223:5)
    at Protocol._delegateError (C:\N\Chat-Simples-para-implementacao\chat-demonstracao\chat-backend\node_modules\mysql\lib\protocol\Protocol.js:398:10)
    at Protocol.end (C:\N\Chat-Simples-para-implementacao\chat-demonstracao\chat-backend\node_modules\mysql\lib\protocol\Protocol.js:116:8)
    at Socket.<anonymous> (C:\N\Chat-Simples-para-implementacao\chat-demonstracao\chat-backend\node_modules\mysql\lib\Connection.js:94:28)
    [... lines matching original stack trace ...]
    at processTicksAndRejections (internal/process/task_queues.js:81:21) {
  fatal: true,
  code: 'PROTOCOL_CONNECTION_LOST'
}

**Comment by Vinicius-Santos-Guedes** [comment]
Vou ligar o computador e te respondo

Em dom, 23 de fev de 2020 17:48, MillesC <notifications@github.com>
escreveu:

**Comment by Vinicius-Santos-Guedes** [comment]
peço desculpa, e agradeço por ter identificado o erro, rode o backend com o
comando `yarn nodemon src/index.js`. Atulizei o Readme.md do github

Em dom., 23 de fev. de 2020 às 17:50, Vinicius Guedes <
viniciusstguedes@gmail.com> escreveu:

**Comment by Vinicius-Santos-Guedes** [comment]
Foi erro meu não ter explicado antes, mas use o comando yarn nodemon src/iex.js para iniciar o backend
